name: 'Build Test'

on:
  push:
    branches:
      - '**'

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Running Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: ${{ matrix.node-version }}
      # Actual Tests
      - run: npm i
      - run: npm run lint --if-present
      - run: npm run typecheck --if-present
      - run: npm run bundle --if-present
      - run: npm run test --if-present
